### ISSUE TITLE
max_log_likelihoods, max_log_likelihoods_index = log_likelihoods.max(dim=0) IndexError: max(): Expected reduction dim 0 to have non-zero size.

### ISSUE THREAD

**Issue by Jean497** [daquang/YAMDA#12]
python3 ./YAMDA/YAMDA-0.1/run_em.py -f 0.1 -r -e -w 20 -maxs 20000 -i ./raw_data/positive_sequence/R5_LUNG_M_2_positive_seq_uniq_name.fa -j ./raw_data/negtive_sequence/R5_LUNG_M_2_negtive_seq_uniq_name_paired.fa -oc ./motif_find/R5_output/LUNG
Loading sequences from FASTA
Searching positive sequences: 100%|███████████████████████████████████████████████████████████████████| 9/9 [00:02<00:00,  3.70it/s]
Searching negative sequences: 100%|███████████████████████████████████████████████████████████████████| 9/9 [00:02<00:00,  3.79it/s]
Converting letter sequences to tensors
Pass 1/1: 100%|██████████████████████████████████████████████████████████████████████████████████| 230/230 [00:00<00:00, 297.42it/s]
On-line EM: 100%|█████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.29it/s]
Pass 1/1: 100%|█████████████████████████████████████████████████████████████████████████████████| 230/230 [00:00<00:00, 1058.46it/s]
Batch EM: 100%|███████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.58it/s]
Computing log likelihood: 100%|█████████████████████████████████████████████████████████████████| 230/230 

[00:00<00:00, 1831.33it/s]
Traceback (most recent call last):
  File "./YAMDA/YAMDA-0.1/run_em.py", line 139, in <module>
    main()
  File "./YAMDA/YAMDA-0.1/run_em.py", line 124, in main
    seqs, seqs_neg = model.fit(seqs, seqs_neg)
  File "/public1/yaoj/SELEX/YAMDA/YAMDA-0.1/yamda/mixture.py", line 126, in fit
    max_log_likelihoods, max_log_likelihoods_index = log_likelihoods.max(dim=0)
IndexError: max(): Expected reduction dim 0 to have non-zero size.

**Comment by Jean497** [comment]
Do you know how to deal with it?
